### ISSUE TITLE
Returning all used cells in a workbook

### ISSUE THREAD

**Issue by bradbase** [fortfall/pyxlsx#1]
Hey @fortfall,

Are you considering a feature that returns all used cells in an archive?

I've written https://github.com/bradbase/xlcalculator which uses dictionaries to manage cells, ranges, defined names and formulas. I would love to use openpyxl to replace my somewhat crappy attempt at Excel archive reading but I couldn't find an easy enough way to get openpyxl to return things in a form that I can use.

Your project gets really close to what I'm looking for eg; the dict-style wrapper for openpyxl. But I need to be able to traverse the cells, ranges and formulas in a way that openpyxl isn't natively built for. I guess currently I load things eagerly and other projects I've seen that use openpyxl are into lazy loading.

Even if you don't see implementing such a feature, can you see a pathway through to there?

**Comment by fortfall** [comment]
I'm not sure whether traverse means something like below?
```python
from openpyxl import Workbook, load_workbook
from openpyxl.worksheet.worksheet import Worksheet
wb: Workbook = load_workbook(filename):
ws: Worksheet = wb.active
for c in ws._cells:
    if c.data_type == 'f' or c.data_type == 'e':
        # c is a cell with formula
        pass
    # cell operation
```

**Comment by bradbase** [comment]
Yes, that kind of thing. For all sheets.

Sort of.;
```python
from openpyxl import Workbook, load_workbook
from openpyxl.worksheet.worksheet import Worksheet
wb: Workbook = load_workbook(filename):
worksheets = wb.sheets

cells = {}
formulae = {}
for worksheet in worksheets:
    for c in worksheet ._cells:
        if c.data_type == 'f' or c.data_type == 'e':
            # c is a cell with formula
            formulae[c.coordinate] = c.value

        cells[c.coordinate] = c
```
I was hoping to avoid a nested for loop going sheet to sheet, cell to cell.

Maybe I should just give it a go and see what the performance looks like.

Cheers, thank you.

**Comment by fortfall** [comment]
It won't be expensive. 
The field _cells is actually a Dict[Tuple(int, int), Cell], so the iteration becomes:
```python
from openpyxl import Workbook, load_workbook
from openpyxl.worksheet.worksheet import Worksheet
wb: Workbook = load_workbook(filename):
ws: Worksheet = wb.active
for coord, c in ws._cells.items():
    if c.data_type == 'f' or c.data_type == 'e':
        # c is a cell with formula
        pass
    # cell operation
```

**Comment by bradbase** [comment]
Damn.

What I need appears to be less than straightforward in openpyxl. Maybe I'm just not "clicking"/grokking with openpyxl..

I was hoping to use openpyxl for Excel file parsing and to facilitate creating structures like these;
```
cells = { 'Sheet1!A1' : Cell(address, value, formula),
'Sheet1!A2' : Cell(address, value, formula),
'Sheet1!A3' : Cell(address, value, formula),
'Sheet1!A4' : Cell(address, value, formula),
'Sheet2!B1' : Cell(address, value, formula),
'Sheet2!B2' : Cell(address, value, formula)
}

formulae = {
'Sheet2!B1' : Formula(formula),
'Sheet2!B2' : Formula(formula)
}

ranges= {
'Sheet3!A1:B2' : Range('Sheet3!A1:B2', cells[ [Cell('Sheet3!A1', value, formula), Cell('Sheet3!B1', value, formula)], [Cell('Sheet3!A2', value, formula), Cell('Sheet3!B1', value, formula)]])
}
```

Obviously openpyxl can help me get there but I need to open the file in each of the two modes to iterate all the worksheets twice (once for data_only and once to collect the formulas). That feels reasonably expensive. I'm playing with Excel files which have a lot of cells.

Is this a use case you can see being supported by your library?

**Comment by fortfall** [comment]
No. My lib opens two copies of the xlsx file too. One for formulas, and one for data_only values. 

openpyxl doesn't evaluate formulas, but caches evaluated results from application like Excel or LibreOffice. When formulas are directly written to xlsx file with openpyxl and the file is not opened with applications, the data_only version would read cell data_only values as None since there are no evaluated results cached. In my script, pycel is used to evaluate formulas when no cached result is available.

**Comment by bradbase** [comment]
PyCel is good.

I've written xlcalculator which also evaluates formulas. It's very young (~3 weeks old) so is still playing up quite a bit.

I've written an Excel file loader and parser for xlcalculator but I think it's crap. It reads values (when cached) and formulas in one pass. It doesn't follow all the rules to correctly support reading Excel files correctly. And I have a feeling it's significantly slower than it needs to be. I am continually hoping to find a library that I can outsource the file reading and parsing but everything is starting to point to openpyxl.

Thanks for your input. I really appreciate your time and effort.

I've starred and am following this project as I'm interested to see how you go with it.

Cheers

**Comment by fortfall** [comment]
I'll work to get rid of double reading xlsx file if time allows.

**Comment by fortfall** [comment]
Now both cell value and cached formula result (if any) are parsed at one time.
```python
from pyxlsx import Workbook, Worksheet, open_xlsx
wb: Workbook = open_xlsx(filename)
for ws in wb:
    for coord, cell in ws._cells.items():
        if cell.is_formula:
            cache = cell.cache  # read cached formula result
            cache_type = cell.cache_type  # read cached formula result type
            formula_str = cell.value  # read formula string
        else:
            value = cell.value  # read value
            data_type = cell.data_type  # read value type
```

**Comment by bradbase** [comment]
I was about to say I found this: https://openpyxl.readthedocs.io/en/stable/tutorial.html#values-only

But you've proper solved it.

I'm re-writing my file handling and am now attempting to use your library.

Cheers :D

I think this issue is well solved.
